version: '3'
services:

  elasticsearch:
    image: "elasticsearch:6.7.2"
    domainname: pontus-demo.com
    ports:
      - "9200:9200"
      - "9300:9300"
    restart: on-failure
    privileged: false
    hostname: elasticsearch
    container_name: elasticsearch.pontus-demo.com
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    networks:
      - pontusvision
    ulimits:
      memlock:
        soft: -1
        hard: -1


  graphdb-nifi:
    image: "pontusvisiongdpr/pontus-track-graphdb-nifi"
    domainname: pontus-demo.com
    ports:
      - "8182:8183"
      - "8183:8183"
      - "7000:7000"
      - "3001:3001"
    restart: on-failure
    privileged: false
    hostname: graphdb-nifi
    container_name: graphdb-nifi.pontus-demo.com
    depends_on:
      - elasticsearch
    networks:
      - pontusvision
    command: >
      /bin/bash -c "
        echo Waiting for elasticsearch service start...;
        while ! nc -z elasticsearch 9200;
        do
          sleep 1;
        done;
        echo Connected!;
        LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/tmp /opt/pontus-graphdb/graphdb-current/bin/pv-gdpr-graphdb.sh /opt/pontus-graphdb/graphdb-current/conf/gremlin-server-nifi.yml
      "


  pontus-nifi:
    image: "pontusvisiongdpr/pontus-extract-nifi"
    domainname: pontus-demo.com
    ports:
      - "8080:8080"
      - "5006:5006"
    restart: on-failure
    privileged: false
    hostname: pontus-nifi
    container_name: pontus-nifi.pontus-demo.com
    depends_on:
      - graphdb-nifi
    networks:
      - pontusvision
    command: >
      /bin/bash -c "
        echo Waiting for graphdb-nifi service start...;
        while ! nc -z graphdb-nifi 8183;
        do
          sleep 1;
        done;
        echo Connected!;
        ../scripts/start.sh
      "

  pontus-timescaledb:
    image: "timescale/timescaledb"
    domainname: pontus-demo.com
    ports:
      - "5432:5432"
    restart: on-failure
    privileged: true
    hostname: pontus-timescaledb
    container_name: pontus-timescaledb.pontus-demo.com
    networks:
      - pontusvision
    depends_on:
      - pontus-nifi
      - graphdb-nifi

    command: >
      /bin/bash -c "
         getent hosts graphdb-nifi.pontus-demo.com
         getent hosts pontus-nifi.pontus-demo.com
      "


  timescale:  


networks:
  pontusvision:
